# Generated by Django 5.0.1 on 2024-02-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
