# Generated by Django 5.0.1 on 2024-02-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
