# Generated by Django 5.0.1 on 2024-02-07 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='A',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='B',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='C',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='D',
            new_name='d',
        ),
        migrations.AlterField(
            model_name='question',
            name='true_ans',
            field=models.CharField(help_text='For example: a or b ', max_length=200),
        ),
        migrations.CreateModel(
            name='CheckAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_question', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Checkquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_ans', models.CharField(max_length=1)),
                ('is_true', models.BooleanField(default=False)),
                ('checktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.checkanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.question')),
            ],
        ),
    ]
