# Generated by Django 5.0.1 on 2024-02-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_rename_a_question_a_rename_b_question_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkanswer',
            old_name='find_question',
            new_name='finded_question',
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.category'),
        ),
    ]
