# Generated by Django 5.0.1 on 2024-02-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_test_category_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 18, 25, 34, 810875, tzinfo=datetime.timezone.utc)),
        ),
    ]
