# Generated by Django 5.0.1 on 2024-02-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_remove_test_category_remove_checkanswer_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='profile',
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='quiz_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='test_app.quizprofile'),
            preserve_default=False,
        ),
    ]
