# Generated by Django 5.0.1 on 2024-02-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_remove_attemptedquestion_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='modified',
        ),
    ]
