# Generated by Django 5.0.1 on 2024-02-12 05:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_remove_quizprofile_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizProfile',
            new_name='SolveProfile',
        ),
    ]
